name: naviguider
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  page_transition: "^1.1.5"
  cupertino_icons: ^0.1.0
  photo_view: ^0.9.2
  zoomable_image: ^1.3.1
  qrscan: ^0.2.17


dev_dependencies:
  flutter_test:
      sdk: flutter
  

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - images/LXBuilding.jpg
    - images/Map13.jpg
    - images/map1.JPG
    - images/oro.jpg
    - images/map3.JPG
    - images/map_with_marker1.JPG
    - images/map_with_marker2.JPG
    - images/LearningSpace1.jpg
    - images/ProjectorRoom.jpg
    - images/LearningSpace1.jpg
    - images/LearningSpace2.jpg
    - images/learningSpace3.jpg
    - images/locker2.jpg
    - images/oro.png
    - images/BehideOro.jpg
    - images/Loker1.jpg
    - images/Locker.jpg
    - images/paint.jpg
    - images/tae.jpg
    - images/poom.jpg
    - images/GateSola.jpg
    - images/EntreShowCase.jpg
    - images/QRBesignOro.JPG
    - images/QRCB2Gate.JPG
    - images/QRCenterOfLxMap.JPG
    - images/QREmerialRiverGate.JPG
    - images/QRMcShowRoomMap.JPG
    - images/QROroGateMap.JPG
    - images/QRPopupExhibitionGateMap.JPG
    - images/QRVendingMachineGateMap.JPG
  fonts:
    - family: InriaSans
      fonts:
        - asset: fonts/InriaSans-Regular.ttf
          style: italic
  
        - asset: fonts/InriaSans-Italic.ttf
